python intersect_atac_rnaseq.py rna_cell_cycle_GO_term/earlyG1_vs_SG2M_Down_heatmap.txt atac_fold_change/earlyG1_vs_SG2M_Down_heatmap.txt intersection/earlyG1_vs_SG2M_Down.txt
python intersect_atac_rnaseq.py rna_cell_cycle_GO_term/earlyG1_vs_SG2M_Up_heatmap.txt atac_fold_change/earlyG1_vs_SG2M_Up_heatmap.txt intersection/earlyG1_vs_SG2M_Up.txt
python intersect_atac_rnaseq.py rna_cell_cycle_GO_term/lateG1_vs_SG2M_Up_heatmap.txt atac_fold_change/lateG1_vs_SG2M_Up_heatmap.txt intersection/lateG1_vs_SG2M_Up.txt
python intersect_atac_rnaseq.py rna_cell_cycle_GO_term/lateG1_vs_SG2M_Down_heatmap.txt atac_fold_change/lateG1_vs_SG2M_Down_heatmap.txt intersection/lateG1_vs_SG2M_Down.txt
python intersect_atac_rnaseq.py rna_cell_cycle_GO_term/lateG1_vs_earlyG1_Down_heatmap.txt atac_fold_change/lateG1_vs_earlyG1_Down_heatmap.txt intersection/lateG1_vs_earlyG1_Down.txt
python intersect_atac_rnaseq.py rna_cell_cycle_GO_term/lateG1_vs_earlyG1_Up_heatmap.txt atac_fold_change/lateG1_vs_earlyG1_Up_heatmap.txt intersection/lateG1_vs_earlyG1_Up.txt
