rm(list=ls())
#library(ggbiplot)
library(data.table)
data=data.frame(read.table('asinh_tpm_minus_sva.tsv',header=TRUE,sep='\t'))
data$Gene=NULL
data.pca=prcomp(t(data),center=TRUE,scale=TRUE)
barplot(100*data.pca$sdev^2/sum(data.pca$sdev^2),width=1,xlim=c(0,13),ylim=c(0,100),xlab="PC",ylab="% Variance Explained")
text(1:12,100*data.pca$sdev^2/sum(data.pca$sdev^2),labels=round(100*data.pca$sdev^2/sum(data.pca$sdev^2),2))

groups=factor(rownames(data.pca$x))
control_treated_groups=factor(c(1,1,1,1,1,1,
                                2,2,2,2,2,2))
time_groups=factor(c(1,1,2,2,3,3,1,1,2,2,3,3))
rep_groups=factor(c(1,1,2,2,3,3,4,4,5,5,6,6))

plot(data.pca$x[,c(1,2)],col=control_treated_groups,pch=16)
text(data.pca$x[,c(1,2)],labels=groups,pos=3,cex=1)
title("PC1 vs PC2")
plot(data.pca$x[,c(1,3)],col=time_groups,pch=16)
text(data.pca$x[,c(1,3)],labels=groups,pos=3,cex=1)
title("PC1 vs PC3")
plot(data.pca$x[,c(2,3)],col=time_groups,pch=16)
text(data.pca$x[,c(2,3)],labels=groups,pos=3,cex=1)
title("PC2 vs PC3")
plot(data.pca$x[,c(3,4)],col=time_groups,pch = 16)
text(data.pca$x[,c(3,4)],labels=groups,pos=3,cex=1)
title("PC3 vs PC4")
plot(data.pca$x[,c(2,5)],col=groups,pch = 16)
text(data.pca$x[,c(2,5)],labels=groups,pos=3,cex=1)
title("PC2 vs PC5") 
