rm(list=ls())
library(limma)
data=read.table("model_comparison_earlyg1_dmso_control",header=TRUE,stringsAsFactors = FALSE,check.names = FALSE)
data$GENE=NULL
png("earlyG1_tpm.png",width=12,height=6,units='in',res=300)
vennDiagram(data[,c(1,3,5,7)],include=c("up","down"),cex=c(1,1,1),counts.col=c("red","green"),circle.col=c("red","green","blue3","yellow"))
dev.off() 
png("earlyG1_exp.png",width=12,height=6,units='in',res=300)
vennDiagram(data[,c(2,4,6,8)],include=c("up","down"),cex=c(1,1,1),counts.col=c("red","green"),circle.col=c("red","green","blue3","yellow"))
dev.off() 

#REPLACE asinh(TPM) with RLOG(counts)
png("earlyG1_rlog.png",width=12,height=6,units='in',res=300)
vennDiagram(data[,c(1,3,9,11)],include=c("up","down"),cex=c(1,1,1),counts.col=c("red","green"),circle.col=c("red","green","blue3","yellow"))
dev.off() 
png("earlyG1_exp_rlog.png",width=12,height=6,units='in',res=300)
vennDiagram(data[,c(2,4,10,12)],include=c("up","down"),cex=c(1,1,1),counts.col=c("red","green"),circle.col=c("red","green","blue3","yellow"))
dev.off() 

############################################################################
data=read.table("model_comparison_lateg1_dmso_control",header=TRUE,stringsAsFactors = FALSE,check.names = FALSE)
data$GENE=NULL
png("lateG1_tpm.png",width=12,height=6,units='in',res=300)
vennDiagram(data[,c(1,3,5,7)],include=c("up","down"),cex=c(1,1,1),counts.col=c("red","green"),circle.col=c("red","green","blue3","yellow"))
dev.off() 
png("lateG1_exp.png",width=12,height=6,units='in',res=300)
vennDiagram(data[,c(2,4,6,8)],include=c("up","down"),cex=c(1,1,1),counts.col=c("red","green"),circle.col=c("red","green","blue3","yellow"))
dev.off() 
png("lateG1_rlog.png",width=12,height=6,units='in',res=300)
vennDiagram(data[,c(1,3,9,11)],include=c("up","down"),cex=c(1,1,1),counts.col=c("red","green"),circle.col=c("red","green","blue3","yellow"))
dev.off() 
png("lateG1_exp_rlog.png",width=12,height=6,units='in',res=300)
vennDiagram(data[,c(2,4,10,12)],include=c("up","down"),cex=c(1,1,1),counts.col=c("red","green"),circle.col=c("red","green","blue3","yellow"))
dev.off() 

data=read.table("model_comparison_sg2m_dmso_control",header=TRUE,stringsAsFactors = FALSE,check.names = FALSE)
data$GENE=NULL
png("sg2m_tpm.png",width=12,height=6,units='in',res=300)
vennDiagram(data[,c(1,3,5,7)],include=c("up","down"),cex=c(1,1,1),counts.col=c("red","green"),circle.col=c("red","green","blue3","yellow"))
dev.off() 
png("sg2m_exp.png",width=12,height=6,units='in',res=300)
vennDiagram(data[,c(2,4,6,8)],include=c("up","down"),cex=c(1,1,1),counts.col=c("red","green"),circle.col=c("red","green","blue3","yellow"))
dev.off() 
png("sg2m_rlog.png",width=12,height=6,units='in',res=300)
vennDiagram(data[,c(1,3,9,11)],include=c("up","down"),cex=c(1,1,1),counts.col=c("red","green"),circle.col=c("red","green","blue3","yellow"))
dev.off() 
png("sg2m_exp_rlog.png",width=12,height=6,units='in',res=300)
vennDiagram(data[,c(2,4,10,12)],include=c("up","down"),cex=c(1,1,1),counts.col=c("red","green"),circle.col=c("red","green","blue3","yellow"))
dev.off() 
